### ISSUE TITLE
Deal with the Basefield property of zexe curve abstractions

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#17]
Zexe ProjectiveCurve and AffineCurve now have Basefield properties and we have to initiate them when we are deriving types for our EngineBLS class.

**Comment by drskalman** [comment]
This is a sub ticket of issue #16

**Comment by drskalman** [comment]
G1's basefield is `PairingEngine::Fq` while G2's basefield is `PairingEngine::Fqe` so we can't commit to any of those field till we decide about our key/signature group assignment. As such we need to abstract out the basefield in the `EngineBLS` definition.

**Comment by burdges** [comment]
I think these base field associated types always existed, so the `EngineBLS` should already ignore them correctly, no?
