### ISSUE TITLE
implement `From<<Self as engine::EngineBLS>::PublicKeyGroupAffine>`

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#18]
I have introduced auxaulary types PublicKey/SignaturePrepared to make the EngineBLS compatible with Zexe Curves but so I need to tell rust how to convert from pairing agnostic curves to the elements prepared specififcally for G1 or G2.

**Comment by burdges** [comment]
If I understand then I did with the two impls for EngingBLS

**Comment by drskalman** [comment]
One actually need to implements From for G1Prepared and G2Prepared and then just tell rust that which one is PublicKeyPrepared and SignaturePrepared is. On the other hand these are implemented in each model (BLS12, ...) in the Zexe crate. So I don't think there is more to do with this at least for now.

**Comment by burdges** [comment]
yes you coudl not impl From for a foreign type anyways
