### ISSUE TITLE
Upgrade `single`.rs to zexe compatible `EngineBLS`

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#19]
In step by step upgrade after upgrading `engine.rs` we should upgrade `single.rs` and perhaps its dependancy.

**Comment by burdges** [comment]
We made some progress but I should take a stab at this.

**Comment by drskalman** [comment]
updated serialization and randomization now dealing with preparation.

**Comment by drskalman** [comment]
add `prepare_publickey` and `prepare_signature` to EngineBLS trait replacing missing `AffineCurve::prepare` method.

**Comment by drskalman** [comment]
add `prepare_publickey` and `prepare_signature` to EngineBLS trait replacing missing `AffineCurve::prepare` method.

**Comment by drskalman** [comment]
8d44845 finishes the upgrade `single.rs`. However there are some points I need to ask @burdges:
1. https://github.com/w3f/bls/blob/skalman-zexe-unprepared/src/single.rs#L665 doesn't fail but https://github.com/w3f/bls/blob/skalman-zexe-unprepared/src/single.rs#L671 can fails what should we do?
2. https://github.com/w3f/bls/blob/skalman-zexe-unprepared/src/engine.rs#L249 I'm curious how to call prepare_g1 instead of re-pasting its body here.

**Comment by burdges** [comment]
Where is `serialize_uncompressed` defined?  I should never fail really.

`prepare_g1::<Engine as PairingEngine>` maybe, but why?  I'd do a default method in the trait, so
```
trait .. {
    ..

    /// Prepare public key for Miller loop
    fn prepare_public_key(g: impl Into<Self::PublicKeyGroupAffine>) -> Self::PublicKeyPrepared {
        let g1: Self::PublicKeyGroupAffine = g.into();
        Self::PublicKeyPrepared::from(g1)
    }

    /// Prepare signature for Miller loop
    fn prepare_signature(g: impl Into<Self::SignatureGroupAffine>) -> Self::SignaturePrepared {
        let g2: Self::SignatureGroupAffine = g.into();
        Self::SignaturePrepared::from(g2)
    }
}
```

**Comment by drskalman** [comment]
> Where is `serialize_uncompressed` defined? I should never fail really.
> 
https://github.com/scipr-lab/zexe/blob/master/algebra-core/src/serialize/mod.rs#L60

**Comment by drskalman** [comment]
> I'd do a default method in the trait

Ah that's much more elegant. But just out of curiosity why this doesn't work:

When I implement the function like this:
```
    fn prepare_public_key(g: impl Into<Self::PublicKeyGroupAffine>) -> Self::PublicKeyPrepared {
        prepare_g1(g)
    }
```

I get this:
```
error[E0284]: type annotations needed: cannot satisfy `<_ as PairingEngine>::G1Affine == <E as PairingEngine>::G1Affine`
   --> src/engine.rs:256:9
    |
256 |         prepare_g1(g)
    |         ^^^^^^^^^^ cannot satisfy `<_ as PairingEngine>::G1Affine == <E as PairingEngine>::G1Affine`

```
And If I implement it like this:
```
    fn prepare_public_key(g: impl Into<Self::PublicKeyGroupAffine>) -> Self::PublicKeyPrepared {
        prepare_g1::<E>(g)
    }
```
I get this:
```
    error[E0599]: no function or associated item named `prepare_g1` found for type parameter `E` in the current scope
   --> src/engine.rs:256:12
    |
256 |         E::prepare_g1(g)
    |            ^^^^^^^^^^ function or associated item not found in `E`
```

Do you know what is the correct way of doing that?

**Comment by burdges** [comment]
Appears rustc has trouble unifying that bound, but really not sure why.  If you've some minimized example or push it into a branch then we could ask someone who knows rustc open issues better.
