### ISSUE TITLE
Upgrade `delinear.rs` to zexe backend

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#21]
This is basically the last module to be upgraded.

**Comment by burdges** [comment]
We should strategize about which of these rogue key defenses we actually require before doing them.  

In fact, there exists a vulnerability in delinear.rs when you've more than 256 signers.  It's interface becomes less nice if one fixes the vulnerability.  

We only care about the proof-of-possession defense anyways, but it's interfaces requires more work too, maybe migrate towards some self certificate trait.

**Comment by drskalman** [comment]
6356a8b closes this issue.
