### ISSUE TITLE
Move TinyBLS to new zexe format

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#22]
tests are failing because we have not ported TinyBLS implementation and I think now that UsualBLS is ported successfully it should be easy to port TinyBLS as well.

**Comment by drskalman** [comment]
@burdges : is this OK or is there a more elegant way of doing this? https://github.com/w3f/bls/commit/44ebfab512b2c7756d2b9eea235ece0fbc91f2d7#diff-ff278ec599adfd033d35a083ebe8948db8bf177c9817dee8ddc4f3a9e3f5728eR289

**Comment by burdges** [comment]
commented there
