### ISSUE TITLE
Resolve the failing bls library tests after backend upgrade

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#24]
- [ ] `test single::tests::single_messages ... FAILED`
- [X] `test delinear::tests::delinearized ... ok`
- [X] `test distinct::tests::distinct_messages ... ok`
- [ ] `test bit::tests::proofs_of_possession ... FAILED`

**Comment by drskalman** [comment]
One problem was with sending vector not as slice as a writer. in that case `writer.write_all` of vector allocate and write after the current length, was making the serialized length 96 bytes instead of 48. That is fixed. Now
  the problem is that bad_signature passes. I need to investigate more.

**Comment by burdges** [comment]
96?  wow, that's odd.

**Comment by drskalman** [comment]
The other problem was hard coded value for hash to curve. which was resloved.
