### ISSUE TITLE
Implement different trait for generating and verifying PoP

### ISSUE THREAD

**Issue by drskalman** [w3f/bls#26]
Sample interface is on the branch: `origin/skalman-pok-new-interface`
 - Generate trait should be implemented by the secret key.
 - Verify trait should be implemented by the public key.

**Comment by burdges** [comment]
I'm not sure we need a trait, either we need a second public key type, or else the sign_pok and verify_pok methods do serialization and deserialization.

**Comment by drskalman** [comment]
f4d137c would
   - [X] rebase the trait divided branch to verify brach.
   - [X] Divide the traits.
   - [X] implement the secret key for first trait.
   - [X] implement the public key for the second trait.
   - [X] test that verification works.

**Comment by drskalman** [comment]
b6ba31d
   - [X] Add extra-message for proof of knowledge.
